name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Build with CoreDNS binary
      run: |
        git clone https://github.com/coredns/coredns
        cd coredns
        go get -u github.com/chinzhiweiblank/coredns-acme@$GITHUB_HEAD_REF
        go mod edit -require=github.com/chinzhiweiblank/coredns-acme
        echo 'acme:github.com/chinzhiweiblank/coredns-acme' >> plugin.cfg
        go get -u && go build
      
