name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -v ./...

    - name: Build with CoreDNS binary
      run: |
        git clone https://github.com/coredns/coredns
        cd coredns
        go get github.com/chinzhiweiblank/coredns-acme
        go mod edit -require=github.com/chinzhiweiblank/coredns-acme@v1.0.1
        go mod tidy
        echo 'acme:github.com/chinzhiweiblank/coredns-acme' >> plugin.cfg
        go mod download github.com/chinzhiweiblank/coredns-acme@v1.0.1
        make